spring:
  kafka:
    bootstrap-servers: 192.168.3.44:9092
    consumer:
      group-id: kafka.transcode.task
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
